### PR TITLE
Unittest feature implementation

### PR DESCRIPTION
**Pull request by VarunSharma15**
### Description

This PR adds support for Unittest feature in dbt-teradata

### Checklist
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` with information about my change

### CODE REVIEW

**Comment by VarunSharma15** [comment]
Tests Result

image

**Comment by tallamohan** [comment]
Do we need to update anything in README?

**Comment by VarunSharma15** [comment]
Readme changes are not required @tallamohan

**Review by tallamohan — APPROVED** [review]
Looks Good

**Review by satish-chinthanippu — APPROVED** [review]

**Pull request merged**
