### PR TITLE
Improve performance of dbt docs generate

### LINKED ISSUE #8: Improve performance of dbt catalog generation
### Describe the feature
Today, `dbt-teradata` adapter collects catalog information one relation at a time. For larger schemas, this approach generates multiple queries to Teradata. It should be possible to replace the current implementation with a single query that joins `DBC.tablesV` and `DBC.ColumnsV`. In fact, this is the approach used in `dbt/include/teradata/macros/catalog.sql`. `dbt/adapters/teradata/impl.py` overrides `get_catalog()` method which uses `dbt/include/teradata/macros/catalog.sql`. Instead, the custom implementation of `get_catalog()` uses `get_columns_in_relation` per table found in a database.

### Describe alternatives you've considered
N/A

### Additional context
N/A

### Who will this benefit?
People using `dbt docs generate`.

### PR DESCRIPTION
**Pull request by eetu-h**
resolves #8 

### Description

Improve the performance of `dbt docs generate`. Inspired by the logic in the [dbt-clickhouse adapter](https://github.com/silentsokolov/dbt-clickhouse/). As a part of the change, changed the logic in catalog.sql.

### Checklist
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` with information about my change

### CODE REVIEW

**Comment by adamtwo** [comment]
@eetu-h , thank you for this contribution :). I ran our CI tests and it found a discrepancy in the metadata output for a column:
https://github.com/Teradata/dbt-teradata/runs/6325734357?check_suite_focus=true

There is a column in a test table of type CHARACTER, but dbt with this PR did not recognize it. 
```
Assert failed for .nodes["model.teradata.view_from_source"].columns.animal.type . Was N/A, but expected CHARACTER.
```
A similar asertion for another materialization passed, so I'm thinking the large case statement that maps column type symbols to their full names is OK:
```
Assert successful for 'CHARACTER' and '.nodes["seed.teradata.test_table"].columns.animal.type'
```

I'm thinking the issue might be with the code for metadata retrieval. It might be that the code in this PR prevents dbt from fetching metadata for source tables. It takes extra effort to get sources right as they may live in schemas other than the base project schema.

If the GH Actions logs do not allow you to troubleshoot, you may want to run the test locally. If it's more productive to set up a joint debug session please contact me at adam.tworkiewicz@teradata.com.

**Comment by eetu-h** [comment]
@adamtwo thank you for running the CI tests! 😊

I think I found the root cause for the failure by looking the `get_columns_in_relation` macro used for metadata retrieval in the current version. I don't personally have an environment available with QVCI enabled but there seems to be the following if-clause in use:

```sql
{% if use_qvci == True -%}
  {{ information_schema_name(relation.schema) }}.ColumnsJQV AS ColumnsV
{% else %}
  {{ information_schema_name(relation.schema) }}.ColumnsV
{%- endif %}
```

I will apply the same to the catalog.sql and once done, would it be possible to rerun the tests?

**Comment by adamtwo** [comment]
Thanks Eetu, that did the trick. I had to tweak it a little bit to ensure that there were spaces between query elements (https://github.com/Teradata/dbt-teradata/commit/39f5e9d27057f4e8a1359c81e6270c1985d1d691). Once I did that I got a clean run.

Before I merge it to `main`, could you please explain how this change makes `dbt docs generate` faster?

**Comment by adamtwo** [comment]
Thanks Eetu, that did the trick. I had to tweak it a little bit to ensure that there were spaces between query elements (https://github.com/Teradata/dbt-teradata/commit/39f5e9d27057f4e8a1359c81e6270c1985d1d691). Once I did that I got a clean run.

Before I merge it to `main`, could you please explain how this change makes `dbt docs generate` faster?

**Comment by eetu-h** [comment]
> I had to tweak it a little bit to ensure that there were spaces between query elements ([39f5e9d](https://github.com/Teradata/dbt-teradata/commit/39f5e9d27057f4e8a1359c81e6270c1985d1d691)). Once I did that I got a clean run.

Thanks Adam! I should have noticed this in my own testing but great that you got it fixed. 😊

> Before I merge it to `main`, could you please explain how this change makes `dbt docs generate` faster?

Once you run `dbt docs generate` in the current version, an own metadata query is run for all database objects (view or table) in all databases used in a dbt project. The query is also executed for all those objects that belong to a database with at least one object referenced in a dbt project.

While in the new implementation, we run a metadata query only once for each database used in a dbt project. The result set contains column metadata for all objects within that database. Depending on the size of your dbt project, this change can lead to huge performance improvements.

**Pull request merged**
