### PR TITLE
Fix incremental strategy column listing

### LINKED ISSUE #120: Incremental Materization : Merge not working when update does single column
### Describe the bug
Using A Incremental Materilisation of a single update column cause DBT to abend.

----------------------------------------------------
-- This is a simple BK Process 
-- Surrogate Key : Serial Monotonic 
-- Comments: This could be any table. 

----------------------------------------------------
{{
    config(
        materialized='incremental',
        schema='T_SKEY',
        unique_key='EDW_KEY',
        on_schema_change='fail',
         incremental_strategy='merge',
      index="PRIMARY INDEX ( SOURCE_KEY )"        
    )
}}
-- Get all the Natural Keys
WITH S AS (
    SELECT			NBO.ORG_NUM||'~'||NBO.ORG_TYPE_CODE||'~'||TRIM(NBO.SYSTEM_RECORD_INDICATOR) (VARCHAR(12)) AS SOURCE_KEY
        FROM			{{source('SRCI_RMS_NB','NB_W_INT_ORG_DS')}} AS NBO
        WHERE			RECORD_DEL_IND=0
        AND				END_DT=DATE '3500-12-31'
   )

{% if is_incremental() %}
-- If it is an incremental run then get the last id
   ,SMAX AS (
    SELECT MAX(EDW_KEY) AS MAX_IDW_KEY
        FROM {{this}}

   )
   ,FINAL AS (
   SELECT SOURCE_KEY
         ,ROW_NUMBER() OVER (ORDER BY SOURCE_KEY) + (SELECT MAX_IDW_KEY FROM SMAX) (BIGINT) AS EDW_KEY
        FROM S 
        WHERE NOT EXISTS (SELECT 1 FROM {{this}} AS X WHERE X.SOURCE_KEY = S.SOURCE_KEY)
   )
{% else %}
-- if this is first time then "this" does not exist
   ,FINAL AS (
   SELECT SOURCE_KEY
         ,ROW_NUMBER() OVER (ORDER BY SOURCE_KEY)  (BIGINT) AS EDW_KEY
        FROM S 
   )
{% endif %}
SELECT 
    **SOURCE_KEY
    ,EDW_KEY**
FROM FINAL

### Steps To Reproduce

Created a model as above in models/bk_simple_006.sql , and ran initial , and incremental run. 

dbt -d run --select bk_simple_006

### Expected behavior
The merge statement is not supposed to abend/error out

### Screenshots and log output

1:05:59  Using teradata connection "model.primark_poc.bk_simple_006"
11:05:59  On model.primark_poc.bk_simple_006: /* {"app": "dbt", "dbt_version": "1.6.7", "profile_name": "primark_poc", "target_name": "dev", "node_id": "model.primark_poc.bk_simple_006"} */

    merge into "DWT10T_SKEY"."bk_simple_006" as DBT_INTERNAL_DEST
        using "DWT10T_SKEY"."bk_simple_006__dbt_tmp" as DBT_INTERNAL_SOURCE
        on
                DBT_INTERNAL_SOURCE.EDW_KEY = DBT_INTERNAL_DEST.EDW_KEY

    when matched then update set

            **"SOURCE_KEY" = DBT_INTERNAL_SOURCE."SOURCE_KEY",**

    when not matched then insert
        ("SOURCE_KEY", "EDW_KEY")
    values
        (
            DBT_INTERNAL_SOURCE."SOURCE_KEY", DBT_INTERNAL_SOURCE."EDW_KEY"
        )

11:05:59  teradata adapter: Teradata error: [Version 20.0.0.0] [Session 6304053] [Teradata Database] [Error 3707] Syntax error, expected something like a name or a Unicode delimited identifier or a 'ROWID' keyword between ',' and the 'when' keyword.

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

WINDOWS 10  with latest release dbt-teradata 

(dbt_primark) (base) C:\Users\cwatts\OneDrive - Primark\Documents\dbt_primark\primark_poc>pip show dbt-teradata
Name: dbt-teradata
Version: 1.6.7
Summary: The Teradata adapter plugin for dbt (data build tool)
Home-page: https://github.com/Teradata/dbt-teradata
Author: Teradata Corporation
Author-email: developers@teradata.com
License: UNKNOWN
Location: C:\Users\cwatts\OneDrive - Primark\Documents\dbt_primark\Lib\site-packages
Requires: dbt-core, teradatasql
Required-by:

(dbt_primark) (base) C:\Users\cwatts\OneDrive - Primark\Documents\dbt_primark\primark_poc>

### PR DESCRIPTION
**Pull request by septimit**
resolves #120 

### Description

This patch fixes an issue in the code generating the update part of the merge statement in the incremental strategy by enforcing the unique_key columns are not included in the output statement

### Checklist
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` with information about my change

### CODE REVIEW

**Comment by VarunSharma15** [comment]
Hi @septimit ,

I tried to run your solution and I got below error
```[Teradata Database] [Error 5758] The search condition must fully specify the Target table primary index and 
partition column(s) and expression must match INSERT specification primary index and partition column(s).```

The error that was raised in the bug is no more, but we can see this above error.
I looked for it a little bit and found out this 
https://support.teradata.com/knowledge?id=kb_article_view&sys_kb_id=12d690d21b7879d004be0feddc4bcb63

It says the fix is not yet available.

**Comment by septimit** [comment]
Hi Varun,
I see this as a separate issue and I don't think it needs to be addressed in the implementation of dbt-teradata.
This fix ensures the emitted code has correct syntax; I think it is the responsibility of the user to make the operations respect the indexing requirements of the platform.

**Comment by VarunSharma15** [comment]
Hi Septi,
Yes, I agree. 
I just wanted to know if you faced this issue while testing this fix or if I was the only one ending with the error.
I think we can go forward with your resolution.
Thank you !!

**Review by tallamohan — APPROVED** [review]
Looks Good

**Review by VarunSharma15 — APPROVED** [review]
Looks Good To Me

**Pull request merged**
