### PR TITLE
TypeError: TeradataAdapter.get_catalog() takes 2 positional arguments but 3 were given

### LINKED ISSUE #180: (dbt-teradata 1.8.0) TypeError: TeradataAdapter.get_catalog() takes 2 positional arguments but 3 were given
### Describe the bug
When calling `dbt docs generate`, the `get_catalog` method is called. dbt-core expects the method to take three positional parameters (self, relation_configs, used_schemas), but the implementation takes just two (self, manifest). This causes the command to fail with the following traceback:
```
06:46:58  Building catalog
06:46:58  Encountered an error:
TeradataAdapter.get_catalog() takes 2 positional arguments but 3 were given
06:46:58  Traceback (most recent call last):
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\requires.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\requires.py", line 247, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\requires.py", line 294, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\requires.py", line 332, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\cli\main.py", line 273, in docs_generate
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\task\docs\generate.py", line 290, in run
    catalog_table, exceptions = adapter.get_filtered_catalog(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\Documents\GitHub\dbt\project1\venv\Lib\site-packages\dbt\adapters\base\impl.py", line 1191, in get_filtered_catalog
    catalogs, exceptions = self.get_catalog(relation_configs, used_schemas)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeradataAdapter.get_catalog() takes 2 positional arguments but 3 were given
```

This applies to cbt-core 1.8.3 as well as to 1.8.0.

### Steps To Reproduce
Execute the `dbt docs generate` command.

### Expected behavior
The command  `dbt docs generate` executes without errors.

**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.3
  - latest:    1.8.3 - Up to date!

Plugins:
  - teradata: 1.8.0 - Up to date!
```

**The operating system you're using:**
Windows 11

**The output of `python --version`:**
Python 3.11.3

### PR DESCRIPTION
**Pull request by tallamohan**
resolves #180

### CODE REVIEW

**Comment by septimit** [comment]
you might consider enabling these adapter basic tests as well https://github.com/dbt-labs/dbt-adapters/blob/d6f736956ef0948cb3fa61d2f5a00d4aa9a6a2aa/dbt-tests-adapter/dbt/tests/adapter/basic/test_docs_generate.py

**Review by sc250072 — APPROVED** [review]
LGTM

**Comment by tallamohan** [comment]
@septimit , This test case is not supported in Teradata.
We have separate testcases to test the catalog
`test/catalog`

**Review by VarunSharma15 — APPROVED** [review]
Looks good to me

**Pull request merged**
