### PR TITLE
Support TERA transaction mode in dbt-teradata adapter

### PR DESCRIPTION
**Pull request by tallamohan**
TERA mode support in dbt-teradata

### CODE REVIEW

**Review by VarunSharma15 — APPROVED** [review]
Looks Good to me

**Review by SatishChGit — APPROVED** [review]
Looks good to me.

**Review by VarunSharma15 — APPROVED** [review]
Looks good to me

**Comment by rafaelkrysciak** [comment]
@tallamohan I don't know where to ask questions about this change, so I'm doing it here.
We have issues using ANSI transaction mode because of the string case's sensitivity. So, we would like to switch to TERA transaction mode. I saw your warning in the code, and I would like to understand what side effects can occur when switching from ANSI to TERA transaction mode. Do you have any advice for the migration?
And a second question: when do you plan to release this change?
Your support is very appreciated.

**Comment by tallamohan** [comment]
@rafaelkrysciak ,

The case sensitivity has been handled, and there should be no issue in TERA mode.

Use cases handled in TERA mode:
- Case sensitivity
- Stored procedures which were created in TERA mode

This statement "may not support all use cases" is for customer-specific use cases which we wanted to understand from the users 

There should not be any impact on the migration. Just switching the 'tmode' in the profile.yml is enough.

Patch release 1.7.x with these changes is expected to be released by the end of this month.

**Pull request merged**
